### ISSUE TITLE
missing self.trust_env = False in PACSession 

### ISSUE THREAD

**Issue by sdementen** [carsonyl/pypac#10]
When environment variables HTTPS_PROXY or HTTP_PROXY are defined, and the PACSession detects that no proxy should be used, self.proxies is None and as self.trust_env is not set to False, the proxies defined in the env variables are used instead of no proxy at all.
Adding `self.trust_env = False` in the PACSession.__init__ fixes the issue.

**Comment by carsonyl** [comment]
Interesting point. I think it makes sense to ignore proxy environment variables, but only in the case where a PAC file is in use and it returned a 'DIRECT' result.

The doc for `trust_env` is "Trust environment settings for proxy configuration, default authentication and similar." The "and similar" part concerns me. [Looking at the source](https://github.com/requests/requests/blob/master/requests/sessions.py#L679), it also toggles the use of `REQUESTS_CA_BUNDLE` and `CURL_CA_BUNDLE`.

**Comment by sdementen** [comment]
my use case is the following:
- I have HTTP*_PROXY variable defined for other uses that python/requests (manual resolution of the PAC settings)
- I use requests sometimes when connected to a VPN (using the PAC) sometimes not connected to the VPN (PAC endpoint returning zero lenght response). When using it in the second cases, PyPAC reuses the HTTP*_PROXY while I want no proxy at all.

maybe there is another solution for my case...

**Comment by carsonyl** [comment]
At the moment, I don't think there's a better solution than having your own code set `PACSession.trust_env = False`. I don't think it's safe for PyPAC to do this for people by default, as `trust_env` controls more than whether proxy environment variables are honoured.
