### ISSUE TITLE
Support PAC served without content type header

### ISSUE THREAD

**Issue by schlomo** [carsonyl/pypac#14]
My PAC file is served without a `Content-Type` header. pypac checks for this header and doesn't accept the PAC file if the header is missing.

**Comment by carsonyl** [comment]
Out of curiosity, what software serves a PAC without `Content-Type`?

**Comment by schlomo** [comment]
Could I kindly ask you to release a new version on PyPI? My users need that fix and they install pypac via pip. Thanks a lot!!!

**Comment by schlomo** [comment]
I actually don't know which software serves the PAC without `content-type` header, I am just a user of a corporate proxy and all that infrastructure is out of my reach. Sorry.

**Comment by carsonyl** [comment]
Sure, I'll make a release tonight.

**Comment by carsonyl** [comment]
https://pypi.python.org/pypi/pypac/0.5.0. 🎉

**Comment by schlomo** [comment]
Thanks a lot, you might want to update the tags at the top of the page to reflect the new version:
![image](https://user-images.githubusercontent.com/101384/35153299-41556236-fd26-11e7-8e7a-ea2946d39ec9.png)
