### ISSUE TITLE
Version 0.10.1 has a memory leak

### ISSUE THREAD

**Issue by maximinus** [carsonyl/pypac#32]
This is due to the new dukpy library.

An alternate dukpy fixes this, the merger request is here: https://github.com/carsonyl/pypac/pull/31

**Comment by carsonyl** [comment]
Given the findings in https://github.com/amol-/dukpy/issues/33#issuecomment-418850470, maybe this problem can be mitigated by keeping a `dukpy.JSInterpreter` instance as a global to reuse.

How severe are the leaks you're seeing? PyPAC currently instantiates one `dukpy.JSInterpreter` per `PACFile`, so I'm guessing that your use case involves the creation of many `PACSession` and `PACFile`.

**Comment by maximinus** [comment]
I found the memory leak in dukpy and raised a pull request [here](https://github.com/amol-/dukpy/pull/34) It being a simple one-line addition, I'm hoping the change can be merged easily enough.

**Comment by carsonyl** [comment]
Thanks for fixing the leak in dukpy. I've released PyPAC 0.11.0 in order to depend on it.
