### ISSUE TITLE
pypac with google analytics?

### ISSUE THREAD

**Issue by rikengct** [carsonyl/pypac#36]
Thank you for pypac.
I have used it successfully to make api requests through my pac
This is the code I used:

`def proxyconnect():`
`   from pypac import PACSession, get_pac`
`   return PACSession(get_pac(url='the url of my pac'))`

then

`def myfunction(variable):`
`   session = proxyconnect()`
`   api = 'the api url'`
`   return session.get(api + variable).json()`

This was basically from your usage examples and I found it very helpful for the particular api I needed to get data from

But, I'm also trying to query google analytics. My code is fine when not needing to go through my pac

I'm wondering if you are familiar with the python code provided by google analytics api v4 and if pypac can be made to work through it? I am not so skilled to know what to do.

this is the code I have working (when not needing to go through the proxy)

`from oauth2client.service_account import ServiceAccountCredentials`
`from googleapiclient.discovery import build`

`def initialize_analyticsreporting():`
   `credentials = ServiceAccountCredentials.from_json_keyfile_name(`
          `KEY_FILE_LOCATION, SCOPES)`
`return build('analyticsreporting', 'v4', credentials = credentials)`

`def get_report(analytics, query):`
`return analytics.reports().batchGet(body=query).execute()`

I'm really stuck. Is it possible to set python (I'm using Spyder through anaconda) to always go through a pac when trying to access the internet? (this pac has no user login or password)
Sorry if these questions are too ignorant.

**Comment by carsonyl** [comment]
I'm not familiar with Google's Python SDKs, but if they honour the `HTTP_PROXY` environment variable, you should be able to find success using something like:

```
