### ISSUE TITLE
Allow setting the client ip address

### ISSUE THREAD

**Issue by aslafy-z** [carsonyl/pypac#47]
In order to test our proxy pac, we would like to be able to set the ip address that `myIpAddress` returns.

Would it be possible to have a config key that overwrites this value?

Thanks!

**Comment by SeyfSV** [comment]
Hi,
I am right, that you want to change source IP?
If yes, than you can achieve this by using this [way](https://stackoverflow.com/a/28783656/1570821).
PACSession is a child of requests.Session class, all described for Session is true for PACSession.

**Comment by aslafy-z** [comment]
You are right. Thank you for the details!

**Comment by kaushik853** [comment]
Did you guys able to run this for multiple source ip address?

**Comment by kaushik853** [comment]
> 
> 
> You are right. Thank you for the details!

Did you guys able to run this for multiple source ip address?
