### ISSUE TITLE
Handle special characters in passwords

### ISSUE THREAD

**Issue by githubuser5432** [carsonyl/pypac#49]
You need to handle special characters in proxy passwords e.g. the at @ symbol. StackOverflow suggests URL encoding the passwords.

https://en.wikipedia.org/wiki/Percent-encoding

Other example passwords to test which could mess up when inserted into a URL http(s)://[password here]:username@exampleproxy.com

```
@
@@
www.example.com
https://
\
%40
:
www.example.com&foobar=
```

**Comment by carsonyl** [comment]
Should be fixed in #46, released in v0.13.0 yesterday.
