### ISSUE TITLE
tld 0.11+ is not python 2.7 compatible

### ISSUE THREAD

**Issue by beamerkun** [carsonyl/pypac#51]
https://pypi.org/project/tld/ dropped support for Python 2.7 without bumping major version - I think pypac should act accordingly.

I would gladly submit a pull request to fix that - but I'm not sure what's the preferred way to fix this:
- lock tld version to below 0.11
- drop support for python 2.7

**Comment by carsonyl** [comment]
It looks like tld 0.11.7 brought back Python 2.7 support, so we can dodge this issue for now.
