### ISSUE TITLE
Pypac is not working on Mac without installing install certificates.command and update shell profile.command

### ISSUE THREAD

**Issue by shashanka3799** [carsonyl/pypac#59]
Hi Carsonyl,

            from pypac import PACSession
            s = PACSession()
            r = s.request('GET', url, None, stream=True, verify=self.get_verification_condition(event_data),
                        cookies=cookies)
Above is the piece of code I am running through my .pkg file while building an app using py2app.
I am getting some errors like SSL verify failed even verify is false for Mac OS.
If I run the install certificates.command and update shell profile.command then it works fine but in every system, there is a dependency of python for running those files. 

Thanks in advance,
Shashanka

**Comment by carsonyl** [comment]
Do you have a traceback? PyPAC should be correctly passing the `verify` keyword to Requests. The request for downloading potential PAC files usually has verify on, but it's not clear if that's the problem you're seeing.
