### ISSUE TITLE
no useful pac function to use in the pypac, hope one day can come true the function

### ISSUE THREAD

**Issue by god-lin** [carsonyl/pypac#62]
fail first time
 I try to let itself to find system's proxy setting, while I really set proxy and can visit the goal site, it can't work
fail second time
I try to set the pac url in the code with the get_pac(), I dont know reason, the function result is None ,haha
fail third time
I try to download the pac file, read the pac file content to PACSession, yes, here is the Exception about follow picture.....really bad using tring, I quit haha
![image](https://user-images.githubusercontent.com/34828669/145712459-eb9beb88-762b-46aa-acf7-cf0e9bc6257b.png)

**Comment by carsonyl** [comment]
The screenshot suggests a JavaScript error in the PAC file: `convert_addr` undefined. The dukpy JavaScript engine is strict about the file being correct JavaScript.
