### ISSUE TITLE
Handle Kerberos with Proxy authentication

### ISSUE THREAD

**Issue by Zulzig** [carsonyl/pypac#78]
Hi Carson,

I am opening this case to inquire if we can handle Kerberos authentication with a proxy where this method is necessary.

In the README, it seems that only Basic Authentication credentials are available.

thank for your helps.

Best regards,

**Comment by carsonyl** [comment]
I don't think Requests (or urllib3) have Kerberos proxy support. It would need to be implemented there first, as PyPAC is just a layer on top of Requests.

**Comment by Zulzig** [comment]
Hi Carson,

thank you for your feedback

best regards
